name: Test Push
permissions:
  contents: write
on: workflow_dispatch
jobs:
  publish-stable:
    name: Publish stable
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/main')}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Commit & Push
        env: 
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.name "José Pereira"
          git config user.email "219649101+jomifepe-alt@users.noreply.github.com"
          git commit --allow-empty --no-verify -m "test commit"
          git tag $(date +"%Y-%m-%d_%H-%M-%S")
          git push --follow-tags --verbose
