name: Test Push
permissions:
  contents: write
on: workflow_dispatch
jobs:
  publish-stable:
    name: Publish stable
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/main')}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"

      - name: Push
        run: |
          git commit --allow-empty --no-verify -m "test commit"
          git tag $(date +"%Y-%m-%d_%H-%M-%S")
          git push --follow-tags --verbose
